/**
 * parse-error-classifier tests (FIX-030).
 *
 * The classifier separates EXPECTED tree-sitter partial-parse noise
 * (JSX-in-plain-JS, generated/minified artifacts) from REAL failures so the
 * indexer's warn stream only carries actionable signal.
 */

import { describe, it, expect } from "vitest";
import {
	isExpectedParseError,
	isGeneratedSource,
	isMinifiedSource,
	containsJsx,
	TREE_SITTER_PARSE_ERROR
} from "../../codebase-index/parser/parse-error-classifier.js";

describe("TREE_SITTER_PARSE_ERROR sentinel", () => {
	it("is the canonical partial-results message (positive)", () => {
		expect(TREE_SITTER_PARSE_ERROR).toBe("Parse errors detected (partial results returned)");
	});
});

describe("containsJsx", () => {
	it("detects a closing tag, self-closing element, and fragment (positive)", () => {
		expect(containsJsx("return <div>hi</div>;")).toBe(true);
		expect(containsJsx("return <Widget prop={1} />;")).toBe(true);
		expect(containsJsx("return <>frag</>;")).toBe(true);
	});

	it("does NOT flag comparisons or generics (negative)", () => {
		expect(containsJsx("const ok = a < b && c > d;")).toBe(false);
		expect(containsJsx("const arr: Array<number> = [];")).toBe(false);
		expect(containsJsx("export function f() { return 1; }")).toBe(false);
	});
});

describe("isGeneratedSource", () => {
	it("flags a generated-file header (positive)", () => {
		expect(isGeneratedSource("// @generated by tool\nconst x = 1;")).toBe(true);
		expect(isGeneratedSource("/* DO NOT EDIT. Automatically generated. */")).toBe(true);
	});

	it("does NOT flag ordinary source (negative)", () => {
		expect(isGeneratedSource("export const x = 1;\n// handwritten")).toBe(false);
	});
});

describe("isMinifiedSource", () => {
	it("flags a single very long line (positive)", () => {
		const minified = "var a=" + "1,".repeat(800) + "b=2;";
		expect(isMinifiedSource(minified)).toBe(true);
	});

	it("flags a multi-line file with huge average line length (positive)", () => {
		const huge = Array.from({ length: 10 }, () => "x".repeat(600)).join("\n");
		expect(isMinifiedSource(huge)).toBe(true);
	});

	it("does NOT flag ordinary formatted source (negative)", () => {
		const source = "export function f() {\n\treturn 1;\n}\n".repeat(20);
		expect(isMinifiedSource(source)).toBe(false);
	});
});

describe("isExpectedParseError", () => {
	it("JSX inside a plain .js file is expected (positive)", () => {
		expect(isExpectedParseError("src/app/page.js", "export default () => <div>x</div>;")).toBe(true);
		expect(isExpectedParseError("a/b/comp.mjs", "export default () => <Widget />;")).toBe(true);
	});

	it("generated and minified artifacts are expected (positive)", () => {
		expect(isExpectedParseError("dist/gen.ts", "// @generated\nconst x = 1;")).toBe(true);
		expect(isExpectedParseError("public/app.min.js", "var a=" + "1,".repeat(800) + "b=2;")).toBe(true);
	});

	it("a genuinely malformed hand-written .ts file is REAL (negative)", () => {
		expect(isExpectedParseError("src/broken.ts", "export function f( { return")).toBe(false);
	});

	it("plain-JS without JSX stays REAL (negative)", () => {
		expect(isExpectedParseError("src/util.js", "const ok = a < b; export default ok;")).toBe(false);
	});

	it("never throws on empty or whitespace input (negative)", () => {
		expect(isExpectedParseError("src/empty.ts", "")).toBe(false);
		expect(isExpectedParseError("src/ws.ts", "   \n\n")).toBe(false);
	});
});
