/**
 * parse-error-classifier — separates EXPECTED tree-sitter parse errors from
 * REAL ones so the indexer's warning stream only carries actionable signal
 * (FIX-030).
 *
 * A tree-sitter parse can report `hasError` on inputs that are perfectly
 * valid for their ecosystem but not for the grammar the file was routed to.
 * On a Next.js/React repo (e.g. `9router`) this is dominated by three
 * families, none of which indicates a data-integrity problem:
 *
 *   1. JSX inside a plain `.js`/`.mjs`/`.cjs` file — those extensions route to
 *      the `javascript` grammar, which has no JSX productions. The failure is
 *      a deterministic extension/grammar mismatch, reproduced on every index,
 *      and the visitor still extracts partial symbols.
 *   2. Generated files — headers such as `@generated` / "do not edit" mark
 *      machine output that is not authored source.
 *   3. Minified / bundled files — a single enormous line (or a tiny file whose
 *      average line length is huge) is a build artifact, not hand-written code.
 *
 * Everything else is REAL: a malformed hand-written source file should keep
 * its `warn`-level log and its place in the failure summary. The classifier is
 * pure and never throws; an unreadable/empty input simply yields `false`.
 */

import path from "node:path";

/**
 * The canonical `ParseResult.error` emitted when tree-sitter recovered a tree
 * that still `hasError` (partial results). This is the ONLY error string the
 * expected-vs-real classifier downgrades — timeouts, permission failures and
 * unsupported-extension rejections are never masked.
 */
export const TREE_SITTER_PARSE_ERROR = "Parse errors detected (partial results returned)";

/** Source extensions that route to the NON-JSX JavaScript grammar. */
const JS_GRAMMAR_EXTENSIONS: ReadonlySet<string> = new Set([".js", ".mjs", ".cjs"]);

/** Case-insensitive header markers that flag machine-generated files. */
const GENERATED_MARKERS: readonly RegExp[] = [
	/@generated/i,
	/do not edit/i,
	/automatically generated/i,
	/autogenerated/i,
	/code generated/i,
	/this file is generated/i
];

/** Filename fragments that flag minified / bundled build output. */
const MINIFIED_NAME_PATTERN = /(?:^|[.-])(?:min|bundle|chunk|vendor|polyfills?|runtime)(?:[.-]|$)/i;

/** A line longer than this is treated as a minified line. */
const MINIFIED_MAX_LINE_LENGTH = 1000;

/** Average line length above which a multi-line file is treated as minified. */
const MINIFIED_AVG_LINE_LENGTH = 500;

/** Header window scanned for generated-file markers. */
const HEADER_WINDOW_CHARS = 2048;

/** True when the first bytes carry a machine-generated marker. */
export function isGeneratedSource(sourceCode: string): boolean {
	const head = sourceCode.slice(0, HEADER_WINDOW_CHARS);
	return GENERATED_MARKERS.some((re) => re.test(head));
}

/**
 * True when the source looks minified/bundled: either a single very long line,
 * or a multi-line file whose average line length is implausibly large.
 */
export function isMinifiedSource(sourceCode: string): boolean {
	const lines = sourceCode.split("\n");
	let longest = 0;
	for (const line of lines) {
		if (line.length > longest) longest = line.length;
	}
	if (longest > MINIFIED_MAX_LINE_LENGTH) return true;
	if (lines.length > 5 && sourceCode.length / lines.length > MINIFIED_AVG_LINE_LENGTH) return true;
	return false;
}

/**
 * Heuristic JSX presence: a closing tag, a self-closing element with an
 * attribute, or a fragment. Conservative — plain `a < b` comparisons and
 * generics do not match.
 */
export function containsJsx(sourceCode: string): boolean {
	if (/<\/[A-Za-z][\w.:-]*>/.test(sourceCode)) return true;
	if (/<[A-Za-z][\w.:-]*(?:\s[^<>]*)?\/>/.test(sourceCode)) return true;
	if (/<>/.test(sourceCode)) return true;
	return false;
}

/**
 * Classify a tree-sitter parse error as EXPECTED (benign, downgrade to debug)
 * or not. Only consulted when the parse actually produced an error; a clean
 * parse is never classified.
 *
 * @param filePath   repo-relative path of the parsed file.
 * @param sourceCode full file contents that were parsed.
 * @returns `true` when the error is expected noise (generated / minified /
 *          JSX-in-plain-JS); `false` when it should stay a real failure.
 */
export function isExpectedParseError(filePath: string, sourceCode: string): boolean {
	// 1. Generated / minified build artifacts — never authored source.
	if (isGeneratedSource(sourceCode)) return true;
	if (isMinifiedSource(sourceCode)) return true;

	// 2. Minified-by-name artifacts (e.g. `app.min.js`, `vendor.bundle.js`).
	const ext = path.extname(filePath).toLowerCase();
	const base = path.basename(filePath);
	if (MINIFIED_NAME_PATTERN.test(base) && !base.endsWith(".ts") && !base.endsWith(".tsx")) {
		return true;
	}

	// 3. JSX inside a plain-JS file — the javascript grammar cannot parse it,
	//    so the partial-parse error is a deterministic, expected mismatch.
	if (JS_GRAMMAR_EXTENSIONS.has(ext) && containsJsx(sourceCode)) return true;

	return false;
}
