#!/usr/bin/env node
/**
 * Generate both package binaries from a single source of truth.
 *
 * Historically only `bin/mcp-memory-dashboard.js` was regenerated by the
 * build script while `bin/mcp-memory-server.js` was hand-maintained, so a
 * change to entry-point names would update only one bin (drift). This script
 * is the canonical template for both bins and is invoked from `npm run build`
 * (see package.json `scripts.build`).
 *
 * - `bin/mcp-memory-server.js` routes `dashboard` / `--index` subcommands to
 *   the correct dist entry and defaults to the MCP server.
 * - `bin/mcp-memory-dashboard.js` is the plain dashboard entry.
 */
import fs from "fs";
import path from "path";
import { execFileSync } from "child_process";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const binDir = path.join(rootDir, "bin");

const SHEBANG = "#!/usr/bin/env node\n";

const SERVER_BIN = `${SHEBANG}import { ensureDashboardBuild } from "./ensure-dashboard-build.mjs";

process.env.MCP_SERVER = "true";

const sub = process.argv[2];
if (sub === "dashboard" || sub === "mcp-memory-dashboard") {
	// Rebuild the served UI bundle if stale (no-op when fresh).
	ensureDashboardBuild();
	import("../dist/dashboard/server.js");
} else if (sub === "daemon") {
	// Combined dashboard + MCP daemon (FEAT-DAEMON-001): the worker serves the
	// dashboard UI, so refresh the bundle before routing into server.ts, which
	// dispatches the daemon/--daemon-worker branches.
	ensureDashboardBuild();
	import("../dist/mcp/server.js");
} else if (sub === "--index") {
	// Pass through --index and all subsequent args to server.ts
	import("../dist/mcp/server.js");
} else {
	import("../dist/mcp/server.js");
}
`;

const DASHBOARD_BIN = `${SHEBANG}import { ensureDashboardBuild } from "./ensure-dashboard-build.mjs";

// Rebuild the served UI bundle if the source is newer than dist/ (no-op when
// fresh). Prevents serving a stale dashboard after src/dashboard/ui changes.
// Uses a dynamic import so the build is guaranteed to finish BEFORE the
// server module is evaluated (static imports are hoisted and would race it).
ensureDashboardBuild();

await import("../dist/dashboard/server.js");
`;

function writeBin(filename, content) {
	const target = path.join(binDir, filename);
	fs.writeFileSync(target, content, { mode: 0o755, encoding: "utf8" });
	console.log(`[gen-bins] wrote ${path.relative(process.cwd(), target)}`);
}

/**
 * Read `git rev-parse --short HEAD` in the repo root, or null when git is
 * unavailable (no binary, not a repo, detached CI checkout). Never throws so a
 * missing git can never break the build.
 */
function readGitSha() {
	try {
		return (
			execFileSync("git", ["rev-parse", "--short", "HEAD"], {
				cwd: rootDir,
				encoding: "utf8",
				stdio: ["ignore", "pipe", "ignore"]
			}).trim() || null
		);
	} catch {
		return null;
	}
}

/**
 * Write the build-identity stamp into `dist/daemon-build.json`. The running
 * daemon reads this (see `src/mcp/utils/build-info.ts`) so an operator can tell
 * exactly which build a process is serving — the PERF-009 stale-daemon guard.
 */
function writeBuildStamp() {
	const pkg = JSON.parse(fs.readFileSync(path.join(rootDir, "package.json"), "utf8"));
	const stamp = {
		version: pkg.version,
		gitSha: readGitSha(),
		builtAt: new Date().toISOString()
	};
	const distDir = path.join(rootDir, "dist");
	fs.mkdirSync(distDir, { recursive: true });
	const target = path.join(distDir, "daemon-build.json");
	fs.writeFileSync(target, `${JSON.stringify(stamp, null, 2)}\n`, "utf8");
	console.log(
		`[gen-bins] wrote ${path.relative(process.cwd(), target)} (v${stamp.version}${stamp.gitSha ? `+${stamp.gitSha}` : ""})`
	);
}

fs.mkdirSync(binDir, { recursive: true });
writeBin("mcp-memory-server.js", SERVER_BIN);
writeBin("mcp-memory-dashboard.js", DASHBOARD_BIN);
writeBuildStamp();
