#!/usr/bin/env node
/**
 * Generate both package binaries from a single source of truth.
 *
 * Historically only `bin/mcp-memory-dashboard.js` was regenerated by the
 * build script while `bin/mcp-memory-server.js` was hand-maintained, so a
 * change to entry-point names would update only one bin (drift). This script
 * is the canonical template for both bins and is invoked from `npm run build`
 * (see package.json `scripts.build`).
 *
 * - `bin/mcp-memory-server.js` routes `dashboard` / `--index` subcommands to
 *   the correct dist entry and defaults to the MCP server.
 * - `bin/mcp-memory-dashboard.js` is the plain dashboard entry.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const binDir = path.resolve(__dirname, "../bin");

const SHEBANG = "#!/usr/bin/env node\n";

const SERVER_BIN = `${SHEBANG}process.env.MCP_SERVER = "true";

const sub = process.argv[2];
if (sub === "dashboard" || sub === "mcp-memory-dashboard") {
	import("../dist/dashboard/server.js");
} else if (sub === "--index") {
	// Pass through --index and all subsequent args to server.ts
	import("../dist/mcp/server.js");
} else {
	import("../dist/mcp/server.js");
}
`;

const DASHBOARD_BIN = `${SHEBANG}import '../dist/dashboard/server.js';
`;

function writeBin(filename, content) {
	const target = path.join(binDir, filename);
	fs.writeFileSync(target, content, { mode: 0o755, encoding: "utf8" });
	console.log(`[gen-bins] wrote ${path.relative(process.cwd(), target)}`);
}

fs.mkdirSync(binDir, { recursive: true });
writeBin("mcp-memory-server.js", SERVER_BIN);
writeBin("mcp-memory-dashboard.js", DASHBOARD_BIN);
